/* ------------------------------------------------------------------ */
/*  Amazon sponsored products                                          */
/*                                                                      */
/*  The single source of truth for every Amazon product on the site:    */
/*  the sponsored rows in the browse grid, the Amazon section in        */
/*  search, and the /amazon "view all" page. Empty this array and all   */
/*  three render nothing, so the app stays clean with no sponsors.      */
/*                                                                      */
/*  For each product provide:                                           */
/*    title       — product name shown on the card                      */
/*    url         — the real affiliate link (SiteStripe, tag=verzatv-20)*/
/*    asin        — Amazon product id. Powers the add-to-cart handoff.  */
/*                  Omit ONLY for search links (a search link has no    */
/*                  single product to put in a cart).                   */
/*    imageId     — id of the product photo on Amazon's image CDN. Grab */
/*                  it from the product page: the main image URL looks  */
/*                  like m.media-amazon.com/images/I/<imageId>._SL..jpg */
/*    badge       — small category tag shown on the tile                */
/*    icon        — glyph for the placeholder if the photo fails        */
/*    accent      — [from, to] gradient for the placeholder             */
/*    description — blurb shown in the in-app product modal             */
/*                                                                      */
/*  NOTE ON PRICES: we deliberately do NOT store prices. Amazon's       */
/*  Associates agreement only permits displaying prices pulled from the */
/*  Product Advertising API and refreshed at least every 24 hours, so a */
/*  hardcoded price is both wrong within a week and a terms violation.  */
/*  Shoppers see the live price on Amazon at handoff.                   */
/* ------------------------------------------------------------------ */

export type AmazonIcon =
  | "skincare"
  | "body"
  | "makeup"
  | "dress"
  | "top"
  | "blanket"
  | "drink"
  | "light";

export type AmazonProduct = {
  id: string;
  title: string;
  url: string;
  asin?: string;
  /** Amazon's id for the primary product photo, e.g. "61IQUadfGEL". */
  imageId?: string;
  /**
   * A background-removed copy of the photo exists locally, at
   * /amazon/<id>-<width>.webp. Generated by scripts/amazon-cutouts.py from
   * imageId. Set this and the product floats on the black card instead of
   * dragging Amazon's white studio backdrop along with it.
   */
  cutout?: boolean;
  /** Explicit image override. Wins over everything else. */
  image?: string;
  icon?: AmazonIcon;
  accent?: [string, string];
  badge?: string;
  description?: string;
};

/** Verza TV's Amazon Associates tracking tag. Every outbound link carries it. */
export const AMAZON_TAG = "verzatv-20";

/** The Verza TV Amazon storefront. Fallback "browse everything" destination. */
export const AMAZON_STOREFRONT =
  "https://www.amazon.com/b?node=53629917011&linkCode=ll2&tag=verzatv-20&linkId=1877149370959eec0902c66cb14fb4e5&language=en_US&ref_=as_li_ss_tl";

/**
 * A product photo straight off Amazon's image CDN, at whatever size we ask for.
 *
 * Deliberately NOT the Associates "AsinImage" widget on ws-na.amazon-adsystem.com:
 * that host is an ad-network domain, so every ad blocker drops it and a large
 * share of shoppers would see empty product cards. m.media-amazon.com is the
 * plain CDN — no blocker touches it, and it is faster.
 */
export function amazonImage(imageId: string, size = 800): string {
  return `https://m.media-amazon.com/images/I/${imageId}._SL${size}_.jpg`;
}

/** Widths generated by scripts/amazon-cutouts.py. Keep the two in step. */
const CUTOUT_WIDTHS = [400, 800, 1200];

/** The local cutout at the smallest width that still covers `size`. */
function cutoutImage(p: AmazonProduct, size: number): string {
  const w = CUTOUT_WIDTHS.find((c) => c >= size) ?? CUTOUT_WIDTHS[CUTOUT_WIDTHS.length - 1];
  return `/amazon/${p.id}-${w}.webp`;
}

/** The photo to show for a product, or undefined to fall back to the placeholder. */
export function productImage(p: AmazonProduct, size = 800): string | undefined {
  if (p.image) return p.image;
  if (p.cutout) return cutoutImage(p, size);
  return p.imageId ? amazonImage(p.imageId, size) : undefined;
}

/**
 * Widths we offer the browser. Amazon's CDN resizes on the fly from one master
 * image, so every extra width here is free to us — no assets to store, and the
 * browser downloads exactly one of them.
 *
 * Capped at 1200 on purpose: ask for more than the master and Amazon returns
 * the master rather than upscaling, which would make the `w` descriptor a lie
 * and could have the browser pick a file smaller than it bargained for.
 */
const IMAGE_WIDTHS = [300, 500, 800, 1200];

/**
 * A srcset so each screen gets a crisp image at its own pixel density: a phone
 * at 3x DPI pulls a genuinely high resolution file, while a low-DPI laptop is
 * not made to download it. A single fixed-size src cannot do both — at 500px it
 * looked soft in the product modal, which renders ~420px wide and therefore
 * wants ~1200px of real pixels on a modern phone.
 */
export function productSrcSet(p: AmazonProduct): string | undefined {
  // An explicit override is a single fixed asset — nothing to resize.
  if (p.image) return undefined;
  if (p.cutout) {
    return CUTOUT_WIDTHS.map((w) => `/amazon/${p.id}-${w}.webp ${w}w`).join(", ");
  }
  if (!p.imageId) return undefined;
  const id = p.imageId;
  return IMAGE_WIDTHS.map((w) => `${amazonImage(id, w)} ${w}w`).join(", ");
}

/**
 * Builds an Amazon cart URL that drops EVERY item in one shot, with the Verza
 * affiliate tag attached, and lands the shopper on their Amazon cart ready to
 * check out.
 *
 * This is what makes the in-app bag work: shoppers collect items inside Verza
 * TV, and a single handoff moves the whole bag over. Amazon gives affiliates no
 * checkout API and forbids framing its pages, so payment always completes on
 * amazon.com — this is as close to buying in-app as the program allows.
 *
 * Must stay a GET link (anchor / window.open). A form POST would be blocked by
 * our CSP, which pins form-action to 'self' and Stripe.
 */
export function amazonCartUrl(items: { asin: string; quantity: number }[]): string {
  const params = new URLSearchParams({ AssociateTag: AMAZON_TAG });
  items.forEach((item, i) => {
    params.set(`ASIN.${i + 1}`, item.asin);
    params.set(`Quantity.${i + 1}`, String(item.quantity));
  });
  return `https://www.amazon.com/gp/aws/cart/add.html?${params.toString()}`;
}

/** A product can only be carted if we know which single product it is. */
export function isCartable(p: AmazonProduct): boolean {
  return Boolean(p.asin);
}

/**
 * Matches an Amazon product against a search query. Every product carries the
 * shared "amazon / prime / shop / sponsored" keywords, so searching "amazon"
 * returns ALL products; product-specific words (e.g. "mascara") narrow it.
 * Token-based AND matching, case-insensitive, min 2 chars — same rules as the
 * movie search.
 */
export function amazonProductMatchesQuery(p: AmazonProduct, rawQuery: string): boolean {
  const q = rawQuery.trim().toLowerCase();
  if (q.length < 2) return false;
  const haystack = [
    p.title,
    p.badge ?? "",
    p.description ?? "",
    "amazon",
    "amzn",
    "prime",
    "amazon prime",
    "shop",
    "sponsored",
    "ad",
    "ads",
    "product",
    "products",
    "deal",
    "deals",
    "trending",
  ]
    .join(" ")
    .toLowerCase();
  return q
    .split(/\s+/)
    .filter(Boolean)
    .every((token) => haystack.includes(token));
}

// The live Verza TV Amazon catalog. Beauty, skincare, fashion and cozy home —
// the categories that convert against a micro-drama audience.
export const AMAZON_PRODUCTS: AmazonProduct[] = [
  {
    id: "amzn-medicube-pore-pads",
    title: "medicube Zero Pore Pad 2.0 Toner Pads",
    asin: "B09V7Z4TJG",
    imageId: "71Mcspt-6AL",
    cutout: true,
    url: "https://www.amazon.com/gp/aw/d/B09V7Z4TJG?_encoding=UTF8&pd_rd_plhdr=t&aaxitk=4c9b78033cdd3087e01a61513088d42f&hsa_cr_id=0&qid=1783959200&sr=1-2-9e67e56a-6f64-441f-a281-df67fc737124&pd_rd_w=q4V7O&content-id=amzn1.sym.2fb72bc8-96ef-420d-b08f-c04b69f36507%3Aamzn1.sym.2fb72bc8-96ef-420d-b08f-c04b69f36507&pf_rd_p=2fb72bc8-96ef-420d-b08f-c04b69f36507&pf_rd_r=ZM6TPR25MF7ECRY13NFT&pd_rd_wg=7OrCb&pd_rd_r=418b7a3c-3941-455f-89e8-0a605ce54b04&th=1&linkCode=ll2&tag=verzatv-20&linkId=eec59b28fc955417cf5e0fbc72a743e2&language=en_US&ref_=as_li_ss_tl",
    icon: "skincare",
    accent: ["#EC4899", "#7C3AED"],
    badge: "Skincare",
    description:
      "Dual-textured toner pads formulated with AHA and BHA. The package contains 70 pads; review the Amazon listing and product label for ingredients and directions.",
  },
  {
    id: "amzn-eos-vanilla-cashmere-lotion",
    title: "eos Shea Better Body Lotion, Vanilla Cashmere",
    asin: "B08KT2Z93D",
    imageId: "61IQUadfGEL",
    cutout: true,
    url: "https://www.amazon.com/eos-Cashmere-Moisture-Lightweight-Non-Greasy/dp/B08KT2Z93D?crid=1DMKKRFDBQOCC&dib=eyJ2IjoiMSJ9.QPaNYrCWq56W11ASKYPeaAf4riMPsFLuZKWqBMiWrEZiHYj2YRe6EP7but1lQLhj6U8sI3r5Nby_VtQoOKFfYW-Ywg5XIoSt8bjLm8WNyNGnCbIGCJc6RCdxCcDpTzwwLv_vjS0xLFQ1fX_hbmH2TeaSZ0aazIbiwNIUQTzFaPAmGnJbrFczey5ngr9ongtMV8snnX3YFiICTKtDsQ_cWc8-Dq0HldTjmwdanXmNQGuPp-LGtljq-ltdiYP_VnCWExM5MWjONyKEhLqEiOqd0XPB83SoILIi05bdZ033zDo.xma_yxIElSai3Fu-kfZW_WOeUSqwjCnXrPPkA0Pr9us&dib_tag=se&keywords=eos%2Bshea%2Bbetter%2Bbody%2Blotion%2C%2Bvanilla%2Bcashmere&qid=1783959254&sprefix=eos%2BShea%2BBetter%2BBody%2BLotion%2C%2BVanilla%2BCashmere%2Caps%2C101&sr=8-1&th=1&linkCode=ll2&tag=verzatv-20&linkId=262054032b89c723e802eb0c458f3f45&language=en_US&ref_=as_li_ss_tl",
    icon: "body",
    accent: ["#F59E0B", "#EC4899"],
    badge: "Body care",
    description:
      "Shea body lotion in a Vanilla Cashmere scent. Review the Amazon listing for ingredients, package size, directions, and current seller details.",
  },
  {
    id: "amzn-mighty-patch-original",
    title: "Mighty Patch Original Acne Patches, Variety Pack",
    asin: "B085P3TYPS",
    imageId: "41OzP2cBrUL",
    cutout: true,
    url: "https://www.amazon.com/Mighty-Patch-MP008-Variety-Pack/dp/B085P3TYPS?crid=OY1KIR6YUKG2&dib=eyJ2IjoiMSJ9.G_7UqE1VNz6IpwfKIcsvxQTU8HXSUwU2L147EV3yT-IVYMm0qxvXKcPuxyr2zdauaPXgM0JyrEJlCcDeQ9D-GKM9HNH-n2rYem7CB-G4S48m1k2hLTLWRDK7TDX5_5GILUDtNd0xE55ESY5yQp1IdjxNDmy-DPIqk1sIsd1l5S-T_XvHwxUnr5kXGbfFTll9FuHRqG8iP9_1PFej6CtQL1lB7BV3yoNrjliopcdE1Ryk-aUCiR5uPvSati8kowagZ79tVF1ZuRSi3W923Ob6pKMV_x-6fAx7bioHsIQ2oyI.GpNL8dzvALmgpuZZ2eLE4XbU6KnMJAdUckbbiWtn-7s&dib_tag=se&keywords=Hero%2BCosmetics%2BMighty%2BPatch%2BOriginal&qid=1783959300&sprefix=hero%2Bcosmetics%2Bmighty%2Bpatch%2Boriginal%2Caps%2C114&sr=8-11&th=1&linkCode=ll2&tag=verzatv-20&linkId=14ab9ac6c134ad5a30323e2fcf62c0fe&language=en_US&ref_=as_li_ss_tl",
    icon: "skincare",
    accent: ["#22D3EE", "#3B82F6"],
    badge: "Skincare",
    description:
      "Hydrocolloid acne-patch variety pack. Review the Amazon listing and package directions before use; individual cosmetic results vary.",
  },
  {
    id: "amzn-maybelline-sky-high-mascara",
    title: "Maybelline Lash Sensational Sky High Mascara",
    asin: "B08H3JPH74",
    imageId: "71MQo8pHmBL",
    cutout: true,
    url: "https://www.amazon.com/Maybelline-Volumizing-Buildable-Lengthening-Multiplying/dp/B08H3JPH74?crid=VVXTV4DH4B4B&dib=eyJ2IjoiMSJ9.Aecm-pL2EtxLYPEyeVue1CjiVQ6AnPQvIsSv2yiciZ_4slBmIFnMLC1HoVlr_K-xIFt5YWQEakEF_8aVW4q1et6SUOJeiHZUAu0VOWHzGaz4HSuRa9g-3V34PBRGwfCw8KVE-Gcpuw_CW2codLJ5LZ5eF2K1gjmOHV8cOgvnuDjFJQkGmfUEV2_NTZ_FL4vZfQN09VPf4fa1rrLKyQA6ANNciDRiIOOZ-PgxMztu-zMNyQN0wH-kT6HnrC07puuD-3JSIV_3V0SJY9ImLqlSRu1_aGLmYoYqTofHYMcri9o.xp11wL6vMU5Tc3q2ocJ5zsUSNUP2jgez3MzFChHS1BI&dib_tag=se&keywords=Maybelline%2BLash%2BSensational%2BSky%2BHigh%2BMascara&qid=1783959349&sprefix=maybelline%2Blash%2Bsensational%2Bsky%2Bhigh%2Bmascara%2Caps%2C134&sr=8-6&th=1&linkCode=ll2&tag=verzatv-20&linkId=42770f49dfc83fdc0c325efa3e914552&language=en_US&ref_=as_li_ss_tl",
    icon: "makeup",
    accent: ["#7C3AED", "#EC4899"],
    badge: "Makeup",
    description:
      "Mascara with a flexible brush in the selected shade. Review the Amazon listing for ingredients, directions, and current product details.",
  },
  {
    id: "amzn-biodance-collagen-mask",
    title: "BIODANCE Bio-Collagen Real Deep Mask",
    asin: "B0B2RM68G2",
    imageId: "51ubxqzNGIL",
    cutout: true,
    url: "https://www.amazon.com/Biodance-Bio-Collagen-Tightening-Hydrating-Molecular/dp/B0B2RM68G2?crid=24HGFSYLYAM1I&dib=eyJ2IjoiMSJ9.h2i0eeAZfU9Vi6t89dK_Mwq-2tuSfCV_zXErQdNMBfjdjK2__zxPRWOFId2oggrFHXXaKARi6XJCAxD3cLjeVOCOSackxRdp_lDUJztjQoadpkdxCDiuxPpygEYIFK4rAs1c38sZ6Ip8EIbk1URFsEI-CNjoXVC0uM6yF5HzmHxSThdalnNd0bbyIBkk-IVWEbwMl_EPb-McYMgkeXn9SlW2ilEmtI_jnma9TNDHoxw9-AlbCAWSmukJy-5GrpEb-aMNxGCiWOeSPqGIAZvDhB_LpFfkQ7dEMtQDujm5Tso._twXPunvBzUBvZkOcl0IgHHdwAcntZDHJQL5fPV0OHY&dib_tag=se&keywords=BIODANCE%2BBio-Collagen%2BReal%2BDeep%2BMask&qid=1783959418&sprefix=biodance%2Bbio-collagen%2Breal%2Bdeep%2Bmask%2Caps%2C497&sr=8-6&th=1&linkCode=ll2&tag=verzatv-20&linkId=e2713177aa444c80b552332c40ba448f&language=en_US&ref_=as_li_ss_tl",
    icon: "skincare",
    accent: ["#3B82F6", "#7C3AED"],
    badge: "Skincare",
    description:
      "Overnight hydrogel facial-mask product sold in a multi-pack. Review the Amazon listing for ingredients and directions; individual cosmetic results vary.",
  },
  {
    id: "amzn-prettygarden-satin-maxi",
    title: "PRETTYGARDEN Satin Sleeveless Cocktail Maxi Dress",
    asin: "B0BRSD3BPQ",
    imageId: "51KBy6HsbSL",
    cutout: true,
    url: "https://www.amazon.com/PRETTYGARDEN-Elegant-Sleeveless-Cocktail-Dresses/dp/B0BRSD3BPQ?crid=2N91978ATBN06&dib=eyJ2IjoiMSJ9.ZwXBixuG_8-ipmG6XrMZz9Vcka2pPJ40YtM0nR7UolwZtiihjtUX83SKl0QXb7xrfUOhzEKMi68ipt_mz6HHmYGxUKVHAXo-KUH_qO4oPC9ZfLFoZsBelyNsrgvSg9cxd9H01JUK74KpV_7Sb8LIjl2vWiwwDaXVDr-d-bDZC2km5UEcztWmqW9kWPKjOzfQhSA3bAp9wPZdwkfkHgWZgc27km89Cvrja4X7BtV5zivVvhTaUxIU5Y8AhuXP5s4Vjf2jOec7klPGVD6DuGEHwIK_6xwR5g_buMLX51Dhl5c.2VVgVcJSST-NpycQZmScDcSw8BIVa8GtiflOFpTIQtw&dib_tag=se&keywords=PRETTYGARDEN%2Bsatin%2Bcocktail%2Bmaxi%2Bdress&qid=1783959454&sprefix=%2Caps%2C135&sr=8-6&th=1&psc=1&linkCode=ll2&tag=verzatv-20&linkId=63ffd732e9f53c665d2bb08f9b6373e3&language=en_US&ref_=as_li_ss_tl",
    icon: "dress",
    accent: ["#E0115F", "#7C3AED"],
    badge: "Dresses",
    description:
      "Sleeveless satin-style maxi dress. Review the Amazon listing for current colors, materials, seller details, and the seller's size guide.",
  },
  {
    id: "amzn-zesica-strapless-midi",
    title: "ZESICA Strapless Floral Bodycon Midi Dress",
    asin: "B0FXWCKFRG",
    imageId: "71UczIhC4bL",
    cutout: true,
    url: "https://www.amazon.com/ZESICA-Strapless-Bodycon-Wedding-Cocktail/dp/B0FXWCKFRG?crid=26TVA0K2J9WVP&dib=eyJ2IjoiMSJ9.oXZyHsTU0E5TWkizqo02ZbMfoWhrnv6EXgjXpEs0Rs6lKYBWHFdxa6xm_4XUuEnmLocDa3fJ7l6kCtkQx4XdEdXzoPY2cmNgMyhssfEYHQgzV1UjDDVqr9cZ5-6q7Ztv4rSlKrwP2NIkAG50ZiUAvGaLAHNMSpyKMk5Q0_vnUEqa1ouRTc1LY2uWLzoYWF9l_8xuc_fI2HU1hvWQQJuWCGm9R-Z22vShsf6BiOUWz2HgiTQml6W_azXTqWzS-KgN2e6QGc55E6ADy9VHeomJ0WJSX4GtyhytTs7bNOZwy60.qcBAoFXCSB3sZoabPzggLSvHXujiMJclue56alopJrQ&dib_tag=se&keywords=ZESICA%2Bstrapless%2Bfloral%2Bmidi%2Bdress&qid=1783959486&sprefix=zesica%2Bstrapless%2Bfloral%2Bmidi%2Bdress%2Caps%2C189&sr=8-6&th=1&psc=1&linkCode=ll2&tag=verzatv-20&linkId=cc143e127470da372fc91535ec6b8a04&language=en_US&ref_=as_li_ss_tl",
    icon: "dress",
    accent: ["#EC4899", "#F59E0B"],
    badge: "Dresses",
    description:
      "Strapless floral bodycon midi dress. Review the Amazon listing for current colors, materials, seller details, and the seller's size guide.",
  },
  {
    id: "amzn-anrabess-ribbed-top",
    title: "ANRABESS Ribbed Henley Long Sleeve Top",
    asin: "B0F6C1YBRB",
    imageId: "816DkVhdrHL",
    cutout: true,
    url: "https://www.amazon.com/ANRABESS-Womens-Sleeve-Fashion-Outfits/dp/B0F6C1YBRB?crid=3D5RF5ZBT16KN&dib=eyJ2IjoiMSJ9.2x7NBZMdMXthsWg9WICmUc_704yu0X2fUNEW7iGv7ZZxlD99WnApCYgFQ2cMb391It__BALOHEPBhuOLARZxFB40tM1AjIxsqC2eDr00Ph8brah0e3WFKzz9s9XJrqU7ErrPYFhXrLb02QVGibg3eECy8MAn9kgop3442Ii84TX2IxC2vIrueg1Nv3Qc7SsB2iK86qRaodUxDHm_YVPTTVX31ooPv1fDbsPL0djXT2Ld-01z45SbMuowBGqqOqiAGtz3JvvuKTaOPcGx34y5Zg-6oXNj459bA5PKMdCJShU.7-6e7KQcI220go7-vsnIqj1f0aGKlBeD344WuPFfrFU&dib_tag=se&keywords=ANRABESS%2Bhenley%2Band%2Bribbed%2Btops&qid=1783959515&sprefix=anrabess%2Bhenley%2Band%2Bribbed%2Btops%2Caps%2C172&sr=8-6&th=1&psc=1&linkCode=ll2&tag=verzatv-20&linkId=17aa869957b5f657c1b54640c0ee408c&language=en_US&ref_=as_li_ss_tl",
    icon: "top",
    accent: ["#F59E0B", "#EF4444"],
    badge: "Tops",
    description:
      "Ribbed long-sleeve henley top. Review the Amazon listing for current colors, materials, seller details, and the seller's size guide.",
  },
  {
    id: "amzn-wearable-blanket-hoodie",
    title: "Wearable Blanket Hoodie, Oversized Sweatshirt",
    asin: "B0FHHK3CKT",
    imageId: "81YswxrOSVL",
    cutout: true,
    url: "https://www.amazon.com/PJGGZ-Wearable-Blanket-Sweatshirt-Oversize/dp/B0FHHK3CKT?crid=3Q0HJCF636UWJ&dib=eyJ2IjoiMSJ9.AsShPAZFgGOrCg-mjQ7asHnYPQtvgQbkUVnk3qNHmjrGsKahczBOiQJV06S8fH-EdvtTbO-qsOlwUKwLfXOfwLT9bSM26aZhH9A1JWUugfrkr0pDv0SH3qM3DKYSKGErzzisTRqUACkG1SImAjlhQenXVxuobLAFPIerUYgxTCXfHkfpvgodTHZzX_nO-2qGW9P7r55Tb10t_fgdNXtZw4EfPWvQ7UML5qlzMzEqs3iUpgLsa_PWCP33dVVlcViorAmsfAJRlan9ATLTYTtd6_V85ChpHH_zmBtdVjtpBs0.QT7oy5YB9cRP4sp24b_cGprmkt5FZ3SIYhp4v-qJ_Yw&dib_tag=se&keywords=Wearable%2Bblanket%2Bhoodie&qid=1783959548&sprefix=wearable%2Bblanket%2Bhoodie%2Caps%2C151&sr=8-6&th=1&psc=1&linkCode=ll2&tag=verzatv-20&linkId=28cef4e398ac8e0029f9098852ce1058&language=en_US&ref_=as_li_ss_tl",
    icon: "blanket",
    accent: ["#8B5CF6", "#22D3EE"],
    badge: "Cozy",
    description:
      "Oversized wearable blanket hoodie with a front pocket. Review the Amazon listing for dimensions, materials, care instructions, and seller details.",
  },
  {
    id: "amzn-plush-throw-blanket",
    // Was a bare search link, which meant no product photo and nothing to cart.
    // Now pinned to the top organic result for that same search so the image,
    // the link and the cart all point at one product — Amazon requires a
    // product image to correspond to whatever it links to.
    title: "Bedsure GentleSoft Plush Fleece Throw Blanket",
    asin: "B0157T1ZK2",
    imageId: "917qEKD6XpL",
    cutout: true,
    url: "https://www.amazon.com/dp/B0157T1ZK2?linkCode=ll1&tag=verzatv-20&language=en_US&ref_=as_li_ss_tl",
    icon: "blanket",
    accent: ["#EC4899", "#8B5CF6"],
    badge: "Cozy",
    description:
      "Plush fleece throw blanket. Review the Amazon listing for current colors, dimensions, materials, care instructions, and seller details.",
  },
  {
    id: "amzn-watersy-tumbler",
    title: "WATERSY 40oz Insulated Stainless Tumbler",
    asin: "B0D76368QD",
    imageId: "617y5B0MLPL",
    cutout: true,
    url: "https://www.amazon.com/WATERSY-Tumbler-Insulated-Stainless-Beverages/dp/B0D76368QD?crid=4VAGI1XRGHHQ&dib=eyJ2IjoiMSJ9.aqLaPv7pKvJ7u46ee58yr0iCnHuegzSpbVoMLNnXFPgaG6DtLCOMqfgRDYvA21f9mgMopTt6Yqv6_hQwAOB5dU_JAe7r9z9xKkr03qBKGP6DSevwogPc6rIGLbSdbrstJDIuU8vzt5PFzjutPR2rucXFoUy1BKsWUlGpdqgAQOmKjO4cKiohGRMPjM9Aow0f96sMk2AukoS2312UeuUhyD531QhyjBAPeCvOFoLa2-Xjd7_G_FZed_G-x-aSFoNCNzyz64lVyZb7q_yyuDT5tWtkxQqCpHVPKcIsTPP8-II.MdvudJ_fv5abbghwuJbLTS8ilrr2VdLzhmd4ksF0IQY&dib_tag=se&keywords=Insulated%2B40oz%2Btumbler&qid=1783959605&sprefix=insulated%2B40oz%2Btumbler%2Caps%2C154&sr=8-6&th=1&linkCode=ll2&tag=verzatv-20&linkId=01ce58643b9b19174435e0039c5e980c&language=en_US&ref_=as_li_ss_tl",
    icon: "drink",
    accent: ["#22D3EE", "#3B82F6"],
    badge: "Drinkware",
    description:
      "40-ounce insulated stainless-steel tumbler. Review the Amazon listing for dimensions, lid and straw details, care instructions, and seller information.",
  },
  {
    id: "amzn-sunset-projector-lamp",
    title: "Sunset Projection Lamp, 180 Degree Rotation",
    asin: "B0FNWFRQMQ",
    imageId: "718+8KJVrPL",
    cutout: true,
    url: "https://www.amazon.com/easeking-Projector-Multicolor-180%C2%B0Rotation-Photography/dp/B0FNWFRQMQ?crid=3U7PRUJUI0DTP&dib=eyJ2IjoiMSJ9.HVTfiMHKiyj3-7CTgt6pMGFuH8-EqrxCOQJ9-5E6o7hulETwpvkeEaYPwAYOcMYH4o4RQcu7MYnoDoqmjorUX8xJYIJYgAZcsu_aCkx673YSPEC9aJxhgQrOaEu6WiH_AU9brWszZC4c9QIMH3C1emCgElJ_hP9yZrvh-byenrIYOaaOpNSWrvE7PaN5E2mFvm6xqaDbe11NLyboSHeciUnMk02dejFAReT9RknByFiQY9D_FTmHI3ydDR7rMHtqvow1y2WT3C97tzu8qgP-TRlyhMtPfRxCSWtUQ_sl7Xo.fmkZeyMFtMsRVOxOzaU_b9gS4LVePxaGTOXoxCBD_RQ&dib_tag=se&keywords=Sunset%2BLED%2Blamp&qid=1783959632&sprefix=sunset%2Bled%2Blamp%2Caps%2C173&sr=8-6&th=1&linkCode=ll2&tag=verzatv-20&linkId=fc1c5846795f57064a6ee0dec2262f01&language=en_US&ref_=as_li_ss_tl",
    icon: "light",
    accent: ["#F97316", "#EC4899"],
    badge: "Lighting",
    description:
      "Adjustable 180-degree sunset projection lamp. Review the Amazon listing for power requirements, color modes, dimensions, and seller details.",
  },
];
